/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
    interface UiHelloworld {
        name: string;
    }
}
declare global {
    interface HTMLUiHelloworldElement
        extends Components.UiHelloworld,
            HTMLStencilElement {}
    var HTMLUiHelloworldElement: {
        prototype: HTMLUiHelloworldElement;
        new (): HTMLUiHelloworldElement;
    };
    interface HTMLElementTagNameMap {
        'ui-helloworld': HTMLUiHelloworldElement;
    }
}
declare namespace LocalJSX {
    interface UiHelloworld {
        name?: string;
    }
    interface IntrinsicElements {
        'ui-helloworld': UiHelloworld;
    }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
    export namespace JSX {
        interface IntrinsicElements {
            'ui-helloworld': LocalJSX.UiHelloworld &
                JSXBase.HTMLAttributes<HTMLUiHelloworldElement>;
        }
    }
}
